version: "3.2"
services:

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    container_name: sql1
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Weonlyusesqltogether2020

#  activeMq:
#    container_name: activemq-1
#    hostname: activemq1.vnet
#    build:
#      dockerfile: ./Dockerfile
#      context: ./
